kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-custom-argocd-server-role
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-custom-argocd-server
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-argocd-argocd-server-role